In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os

api_keys='AIzaSyAwu4Ymdzd6swv1zcRw8IJHzi7jc-zvD38'

# Import API key
#from api_keys import g_key

In [2]:
# Store Part I results into DataFrame
# Load the csv exported in Part I to a DataFrame

city_df = pd.read_csv("/Users/mikan/Documents/Data Science Bootcamp/Python_API_Homework/WeatherPy/export_city_df.csv") 
city_df.head()

,City_id,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max_temp,Wind_Speed
0,1015776,Bredasdorp,92,ZA,1583979995,88,-34.53,20.04,19.00,6.20
1,347634,Ţahţā,75,EG,1583980094,31,26.77,31.50,26.00,9.30
2,2236967,Soyo,76,AO,1583980004,87,-6.13,12.37,26.13,0.73
3,3421765,Nanortalik,0,GL,1583979997,72,60.14,-45.24,-3.52,2.32
4,3883457,Lebu,67,CL,1583980239,95,-37.62,-73.65,11.01,0.91

In [8]:
# Humidity Heatmap
# Configure gmaps.
# Use the Lat and Lng as locations and Humidity as the weight. 
# Add Heatmap layer to map. 
# heatmap looks different from the example. no satellite view ... color is different etc???? 

#city_df.dtypes

# Store latitude and longitude in locations
locations = city_df[["Lat", "Lng"]]
locations.head()

# Humidity as the weight
weight_humi=city_df['Humidity']

# Plot Heatmap
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=weight_humi, 
                               dissipating=False, max_intensity=100,
                                point_radius=4)

# Add layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [23]:
# Create new DataFrame fitting weather criteria
# Narrow down the cities to fit weather conditions.
# A max temperature lower than 80 degrees but higher than 70.
# Wind speed less than 10 mph.
# Zero cloudiness.
# Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.

# Note: Feel free to adjust to your specifications but be sure to limit the number of rows returned by your API requests 
# to a reasonable number.

# Create a variable for temeratures in Fahrenheit 
# reference https://www.pythonforbeginners.com/code-snippets-source-code/python-code-celsius-and-fahrenheit-converter
Max_temp_F=(city_df['Max_temp']* 9/5) + 32

# Add this field to city_df
city_df['Max_temp_F'] = Max_temp_F 

# Find rows that meet the 4 conditions 
city_df2 = city_df[((city_df['Max_temp_F'] > 70) & (city_df['Max_temp_F'] < 80)) 
                   &  (city_df['Wind_Speed'] < 10) & (city_df['Cloudiness'] == 0)]

# Drop any rows will null values. 
city_df2.dropna()

city_df2.head()

,City_id,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max_temp,Wind_Speed,Max_temp_F
98,3461425,Ilhabela,0,BR,1583980096,78,-23.78,-45.36,24.40,6.95,75.920
117,3450232,Santa Fé do Sul,0,BR,1583980038,87,-20.21,-50.93,22.34,2.06,72.212
164,3382160,Cayenne,0,GF,1583980203,94,4.93,-52.33,22.00,2.52,71.600
166,3448903,São João da Barra,0,BR,1583980275,82,-21.64,-41.05,22.90,3.85,73.220
187,3617154,Puerto Cabezas,0,NI,1583980280,94,14.04,-83.39,22.39,2.16,72.302

In [ ]:
# Hotel Map

# Store into variable named hotel_df.
# Add a "Hotel Name" column to the DataFrame.
# Set parameters to search for hotels with 5000 meters.
# Hit the Google Places API for each city's coordinates.
# Store the first Hotel result into the DataFrame.
# Plot markers on top of the heatmap.



# 3. Find the name and address of a bike store in Seattle, Washington.
#    Hint: See https://developers.google.com/places/web-service/supported_types
target_type = "hotel" ???
city_coords = city_df2[["Lat", "Lng"]]
radius = 5000

# rewrite params dict

params = {
    "location": city_coords,
    "types": target_type,
    "radius": radius,
    "key": gkey
}

# Build URL using the Google Maps API
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

print("Drill #3: A Bike Store in Seattle, WA")

# Run request
response = requests.get(base_url, params)

# print the response URL, avoid doing for public GitHub repos in order to avoid exposing key
# print(response.url)

city_hotels = response.json()

# Print the JSON (pretty printed)
# print(json.dumps(seattle_bikes, indent=4, sort_keys=True))

# Print the name, city, country of the hotels
print(city_hotels["results"][0]["name"])
print(city_hotels["results"][0]["city"])
print(city_hotels["results"][0]["name"])